### ISSUE TITLE
Installing local-attn-reshape-cuda Requirement

### ISSUE THREAD

**Issue by sanazsab** [cuiaiyu/dressing-in-order#14]
Hi, 

I installed based on the guidance in GFLA, but still there is the below error
ERROR: Could not find a version that satisfies the requirement local-attn-reshape-cuda==0.0.0 (from versions: none)
ERROR: No matching distribution found for local-attn-reshape-cuda==0.0.0

Thanks for your prompt response in advance.

Best
Sanaz

**Comment by sanazsab** [comment]
> GFLA's setup

Thanks for your response. However, yes, I check it out again, still there is a problem

**Comment by jerry940080** [comment]
I got this problem after finishing setup of gfla
Processing /tmp/build/80754af9/cffi_1606255098796/work
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory'/tmp/build/80754af9/cffi_1606255098796/work'

**Comment by sanazsab** [comment]
> Is
> 
> > > GFLA's setup
> > 
> > 
> > Thanks for your response. However, yes, I check it out again, still there is a problem
> 
> Was there any error message pop out when you installed the GFLA's functions?

Yes, Exactly and the error is the same as above.
