### ISSUE TITLE
Run demo dataset

### ISSUE THREAD

**Issue by nastaran1999** [cuiaiyu/dressing-in-order#22]
hi
I want to get output from demo notebook, and I need to download the dataset to do this. But in the link you mentioned in the repo, there are 5 directories and I'm confused about which one should be used. These are the folders inside the provided link:
![Screenshot (509)](https://user-images.githubusercontent.com/34520533/140928711-39bcd290-d725-43bc-894f-a1b198755c84.png)

Could you possibly help me with it?

**Comment by cuiaiyu** [comment]
Please download the ```inshop clothes retrieval -> img -> highres``` (https://drive.google.com/drive/folders/0B7EVK8r0v71pYkd5TzBiclMzR00?resourcekey=0-fsjVShvqXP2517KnwaZ0zw)

**Comment by nastaran1999** [comment]
thanks. I downloaded the img_highres.zip file, and when I want to extract it, it gives me this error for every image exists in the file: unable to get password

![Screenshot (512)](https://user-images.githubusercontent.com/34520533/141110797-2a33ce49-229b-4981-b435-7d5dc43b349e.png)
:


what is the password?

**Comment by cuiaiyu** [comment]
please ask the deepfashion owners for the password. The deepfashion webpage provides a form and instruction about the process http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion.html
