### ISSUE TITLE
Purpose of warm up

### ISSUE THREAD

**Issue by SenHe** [cuiaiyu/dressing-in-order#24]
Hi, 

Thanks for the great work.

I found the model's training requires warm up of the flow estimation model. What's the purpose of this step?
And how to design the warm up?

**Comment by cuiaiyu** [comment]
We use the flow estimation model to do the spatial transformation of feature maps from the source pose to target pose. 

If training from scratch, warm up the flow model will fasten the training. We warmup the flow model in the same way as [GFLA](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/PERSON_IMAGE_ANIMATION.md).
