### ISSUE TITLE
replace costume pictures

### ISSUE THREAD

**Issue by nanfangzhe** [cuiaiyu/dressing-in-order#25]
Thank you for the model provided，which has further improved the field of costume change.Recently,on the basis of the pre training model you provided,we replaced ancient costume and found that all ancient costume pictures have been replaced with tops.I wonder if you can provide some solutions.Thank you very much.

**Comment by cuiaiyu** [comment]
What's the expected output? The demo code is set to replace tops only (with human parsing index 5), so it may has something to do with the virtual try-on setting. If you want to replace the full outfits you may want to set the to-replace garment as [5-top, 1-bottom, 3-jackets]. It will be better if you could clarify the question a bit or give some output pictures to illustrate the problem. Thanks.

**Comment by cuiaiyu** [comment]
What's the expected output? The demo code is set to replace tops only (with human parsing index 5), so it may has something to do with the virtual try-on setting. If you want to replace the full outfits you may want to set the to-replace garment as [5-top, 1-bottom, 3-jackets]. It will be better if you could clarify the question a bit or give some output pictures to illustrate the problem. Thanks.

**Comment by cuiaiyu** [comment]
Seems no longer active. Please reopen if not the case.:)
