### ISSUE TITLE
Installation issues with requirements.txt

### ISSUE THREAD

**Issue by vivekjames** [cuiaiyu/dressing-in-order#26]
Hi there,

When I run the command: `pip install -r requirements.txt`, I run into some issues:

I noticed in "requirements.txt" that there are filepaths included next to some of the dependencies we need to install (cffi, Pillow, pycparser, and six); I removed them and the installations for these dependencies still worked. Is this ok or are there specific versions of these dependencies that we have to install? 

My next issue is that for the following dependencies

mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0

I get "No matching distribution found for [dependency]". I tried removing the version numbers for each and the installations proceeded successfully. Is this ok? 

Thanks in advance!

**Comment by cuiaiyu** [comment]
Sorry for this trouble. I think you can ignore those lines that give the issue. It should be fine.

**Comment by vivekjames** [comment]
Thank you!

**Comment by cuiaiyu** [comment]
> Thank you!

Thanks, I updated the requirement.txt accordingl
