### ISSUE TITLE
AssertionError: data is not a valid directory

### ISSUE THREAD

**Issue by stoneshi-1999** [cuiaiyu/dressing-in-order#28]
Hi !  Cui ,  the work is really COOOOL ! Thanks for ur code. But after setting the environment，I am gonna set the dataset，when I Run `python tools/generate_fashion_dataset.py --dataroot $DATAROOT to split the data.` （which was the **step3** in the Dataset）I met this error...Hope u can help me，thanks a lot❤

--------------------------------------------------

Traceback (most recent call last):
  File ".\tools\generate_fashion_datasets.py", line 77, in <module>
    make_dataset(args.dataroot)
  File ".\tools\generate_fashion_datasets.py", line 31, in make_dataset
    assert os.path.isdir(dataroot), '%s is not a valid directory' % dataroot
AssertionError: data is not a valid directory

-----------------------------------------------------

Do I need to change the **dataroot** in the demo.ipynb?
`dataroot = '/shared/rsaas/aiyucui2/inshop/fashion_yifang'`

**Comment by cuiaiyu** [comment]
Yes, please change the ```opt.dataroot``` to the path you have deepfashion dataset prepared. Thanks.
