### ISSUE TITLE
Cannot reproduce results shown in the Colab demo notebook

### ISSUE THREAD

**Issue by jackylu0124** [cuiaiyu/dressing-in-order#30]
Hi there,

I tried running the demo notebook on both Colab and on my local machine but could not reproduce the results shown in the Colab demo notebook, here are some of the results from my end along with the original ones shown in the Colab notebook for comparisons. The fit looks correct in general, but the head and the skin tone are distorted and could not achieve the same level of fidelity as the ones shown in the original notebook. Do you by chance know why this might be happending and what I should do in order to reproduce the results you had in the demo notebook? Thank you very much in advance!

PyTorch version on Google Colab: `1.10.0+cu111`
PyTorch version on local machine: `1.10.1+cu113`

Original output:
![image](https://user-images.githubusercontent.com/28615340/151085696-3d2ed04f-f0d4-44fb-9d9b-dc20b0e90217.png)
My output:
![image](https://user-images.githubusercontent.com/28615340/151085736-d0317c5b-5b5e-41d4-b348-afe336fd2e9a.png)

Original output:
![image](https://user-images.githubusercontent.com/28615340/151085206-923aa16f-f403-4435-89e3-7cef5fb1294a.png)
My output:
![image](https://user-images.githubusercontent.com/78942094/151083715-1b84bead-97ce-4753-b928-97893c6f0447.png)

Original output:
![image](https://user-images.githubusercontent.com/28615340/151084737-513cb0f9-ea93-4397-8e94-a58d94a7172f.png)
My output:
![image](https://user-images.githubusercontent.com/28615340/151084782-104de29c-ab92-4b45-86c7-23205a11def1.png)

Original output:
![image](https://user-images.githubusercontent.com/28615340/151085322-7219e03d-a12f-44a6-b130-e446a45e7ecf.png)
My output:
![image](https://user-images.githubusercontent.com/28615340/151084639-65899699-1642-48ea-80b5-9d2df7139b3a.png)

**Comment by cuiaiyu** [comment]
It's weird. Which checkpoints are you using? Is the ```opt.netG``` aligned with the checkpoints?

**Comment by jackylu0124** [comment]
I am using the checkpoints in DIORv1_64.zip, it turns out I set `opt.netG = "dior"` earlier and forgot to set it as `opt.netG = "diorv1"` like you said. I can reproduce the exact same results now. Sorry for the inconvenience, but thank you so much for your help and hints!!
