### ISSUE TITLE
no images are printed。。

### ISSUE THREAD

**Issue by stoneshi-1999** [cuiaiyu/dressing-in-order#31]
![image](https://user-images.githubusercontent.com/70521393/151310117-cbadd2f4-98ae-4b0d-bb7f-789d96f34bae.png)

Thank u so much in advance❤❤❤After I [set the dataset](https://github.com/cuiaiyu/dressing-in-order/issues/28) as u say , then I run the demo , no error but no images are printed...

Here's the warnings, I tried to change `align_corners=False` to `align_corners=True` in `.\torch\nn\functional.py` , but it's useless...

```
C:\Users\75643\miniconda3\envs\gfla\lib\site-packages\torch\nn\functional.py:3636: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
C:\Users\75643\miniconda3\envs\gfla\lib\site-packages\torch\nn\functional.py:4007: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
C:\Users\75643\Desktop\0postgraduate\1paper\0_DiOr_repo\dressing-in-order-main\utils\pose_utils.py:91: FutureWarning: circle is deprecated in favor of disk.circle will be removed in version 0.19
  yy, xx = circle(joint[0], joint[1], radius=radius, shape=img_size)
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
```

**Comment by stoneshi-1999** [comment]
![image](https://user-images.githubusercontent.com/70521393/151357523-c6ea4930-5784-4a6b-9325-4a381597e040.png)

And after I run 'pose transfer' block , when I run 'try-on' , I will met this error.  

`Run time error: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0: 6.00 GiB total capacity: 3.62 GiB already allocated: 0 bytes free: 3.72 GiB reserved in total by Pytorch )If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Here's my Chip, maybe the memory is not enough for the Demo? (T_T) 

Chip type: NVIDIA geforce rtx3060 laptop GPU
DAC type: integrated RAMDAC
Device off type: complete display device
Total memory: about 22278mb
Display memory (VRAM): 6023mb
Shared memory: 16255mb

**Comment by cuiaiyu** [comment]
for ```Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).```, check if you have image array in right ```type``` and range. As the error indicated, the image array should have [0..1] for floats or [0..255] for integers). 

For memory, it should be fine for 256x176. Please check ```Nvidia-smi``` to see if there is anything else occupying the memory. Thanks.

**Comment by netsalesbg-ltd** [comment]
Must use `scikit-image<=1.18`. They removed old deprecation, and renamed some functions one of which `circle` was renamed to `disk`. Or if you need the newer version of scikit-image, you should refactor the code to change all `circle` function calls to `disk`.

**Comment by ASIFIQBAL5955** [comment]
Please check this link, all issues have been resolved.
video demo
https://www.youtube.com/watch?v=pRJppKDsZWA&ab_channel=AISOFT
