### ISSUE TITLE
Face is different from the original image 

### ISSUE THREAD

**Issue by kieutrongthien** [cuiaiyu/dressing-in-order#32]
How i can increase quality this image ?. Result is too different from original image.
![image](https://user-images.githubusercontent.com/9605103/152719925-de0fa2f0-dc86-4291-bc68-597339f23a5d.png)

**Comment by kieutrongthien** [comment]
> How i can increase quality this image ?. Result is too different from original image.
> I'm using DIORv1_64, this is my custom image.

 ![image](https://user-images.githubusercontent.com/9605103/152719925-de0fa2f0-dc86-4291-bc68-597339f23a5d.png)

**Comment by cuiaiyu** [comment]
The released model was trained on DeepFashion, and unfortunately, there is some overfitting on faces (as DeepFashion only a few dozens of different faces). You may refer to those Virtual Try-On methods which combines the garment and the other part of the person on image level, in which the face is copied directly from the source images.

**Comment by kieutrongthien** [comment]
> The released model was trained on DeepFashion, and unfortunately, there is some overfitting on faces (as DeepFashion only a few dozens of different faces). You may refer to those Virtual Try-On methods which combines the garment and the other part of the person on image level, in which the face is copied directly from the source images.

So, you mean is if i prepare the dataset with more different faces and results will be improved right?

**Comment by cuiaiyu** [comment]
Yes, a more diverse set of faces would help the collapse/overfitting situation.
