### ISSUE TITLE
Test for high resoluton images

### ISSUE THREAD

**Issue by kieutrongthien** [cuiaiyu/dressing-in-order#33]
I have two images with size 768x1024. How i can test try on but still keep high resolution ?. Do i need to train model with 768x1024 before test it ?.

**Comment by cuiaiyu** [comment]
The released model is only train and test on 256x176, so for higher resolution, it may not have the same behavior and you may need to re-train and tune the hyperparameters.

**Comment by kieutrongthien** [comment]
I think i can try to increase image quality after i have result image from try on. Because my server only have 4 GPU Tesla T4 16GB, it take to 3 - 4 day to train on current size 256 x 176 and use 10GB Memory on GPU 0 and 3GB to the every GPU left. I tried to change size of images to 512 x 384 but it show error CUDA memory not enough.

**Comment by tantom** [comment]
Thank you for the model provided 256 x 176,  Can you release a model trained on 512x352 ?

**Comment by cuiaiyu** [comment]
> 
Ah, I suspect training on a single GPU for 256x176 would be faster than 4 GPUs. 

Unfortunately the code is not well optimized for parallel training, so the memory is not well balanced. If you want to do some optimization, you may try to wrap all separate models (like ```E_attr```, ```Flow```, ```G```) into a unified model before calling ```nn.Parallel``` and get rid of those function calls like ```model.netG.module.something```.

**Comment by NorthanX** [comment]
Hi, is it possible to resize the image into high resolution, like 512*352, and put it into the pretrained models? Thank you

**Comment by kieutrongthien** [comment]
@NorthanX You need to re-train model in higher resolution to make it work

**Comment by NorthanX** [comment]
@kieutrongthien Thanks! So have you done your high quality training? I am still trying to change the parameters of the training process and I am quite curious about the results.

**Comment by kieutrongthien** [comment]
@NorthanX you can use dataset provided in README:

[http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html](http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html)

I trained on higher resolution before but it have a little problem at the face of human in the result, you can check here: #32 

So if you need to improve it, you need to prepare your own dataset with more difference human models.

**Comment by NorthanX** [comment]
@kieutrongthien  I will train with the original deepfashion inshop dataset first. Thanks for your advice!

**Comment by Garfield2013** [comment]
1. Does this project work for you guys - when I tried it out some time ago
I didn’t manage to get the code running (can’t remember the exact reason
now)?

2. It would be great if you could create a new repo here in Git with all
the fixes and changes you did to make it work - especially with a higher
resolution model included 🤓👍🏼

tir. 5. jul. 2022 kl. 11.23 skrev NorthanX ***@***.***>:

**Comment by NorthanX** [comment]
@Garfield2013 
1. The demo code works for me.
2. I am not sure about the process of higher resolution training, and I am still trying to change the parameter. But if there is any progress, I will update a repo and let you know.

**Comment by Garfield2013** [comment]
Great! Thank you so much! 🤓👍🏼

ons. 6. jul. 2022 kl. 06.24 skrev NorthanX ***@***.***>:

**Comment by vinodbukya6** [comment]
Hi @kieutrongthien 
I hope you are doing good. Have you trained on higher resolution images? I am looking for virtual tryon on high resolution images. Did you get same performance as 256x176 dataset? 

> I trained on higher resolution before but it have a little problem at the face of human in the result, you can check here: #32

**Comment by kieutrongthien** [comment]
> Hi @kieutrongthien I hope you are doing good. Have you trained on higher resolution images? I am looking for virtual tryon on high resolution images. Did you get same performance as 256x176 dataset?
> 
> > I trained on higher resolution before but it have a little problem at the face of human in the result, you can check here: #32

You can get same performance with higher resolution. I tried on 512x384 before, only 1 problem is the face of the result. 

If you want to get better result, you need to put more images with difference faces in to the dataset.

**Comment by vinodbukya6** [comment]
@kieutrongthien 
If possible can you please share pre-trained models of high resolution images?

**Comment by vinodbukya6** [comment]
Hi @kieutrongthien 
Is it possible to share the models?

**Comment by kieutrongthien** [comment]
> Hi @kieutrongthien Is it possible to share the models?

Sorry, I can't share pretrained model to you, my model trained on edited source code of this repository. So it will not work with original source code.

**Comment by vinodbukya6** [comment]
Okay. No problems!!!
