### ISSUE TITLE
What is the meaning of atr2aiyu and aiyu2atr?

### ISSUE THREAD

**Issue by fyviezhao** [cuiaiyu/dressing-in-order#34]
Hi, could you tell me what `atr2aiyu` and `aiyu2atr` mean [here](https://github.com/cuiaiyu/dressing-in-order/blob/314bd905786e24b14b3f792c7739be2626bc6249/datasets/deepfashion_datasets.py#L54)? Why we need this additional label transfer instead of directly using the raw parsing labels?

**Comment by cuiaiyu** [comment]
Hi, ```aiyu``` is a label set following our prior work [ADGAN](https://arxiv.org/pdf/2003.12267.pdf)'s label definition (see [section 3.3 - implementation details](https://arxiv.org/pdf/2003.12267.pdf)). ```atr2aiyu``` and ```aiyu2atr``` are the dictionary used for label conversion. Sorry for the bad naming. 

The reason to set up this label conversion is to follow and compare with the prior work ADGAN. Directly using the raw parse should also work.

**Comment by cuiaiyu** [comment]
closed as no longer active. Please reopen if needed. :)
