### ISSUE TITLE
Generate Datasets error

### ISSUE THREAD

**Issue by pranay-simejia** [cuiaiyu/dressing-in-order#35]
Hi! Congratulations on the great work. I was trying to set up the repo on my windows 11 local machine but getting a list index out of bounds error while generating the dataset. Could you suggest possible solutions?

![image](https://user-images.githubusercontent.com/70064696/153258868-44a07a7f-6b40-4f75-9fdf-ca87edce5730.png)

**Comment by KIMMUSIC** [comment]
In window, path is "$DATAROOT\\img_highres\\MEN\\~"
So I changed split("/") to split("\\") at 52,53 lines.
Then, it works well

**Comment by shu0o0yX** [comment]
@pranay-simejia Hi, could you please share img_highres.zip with me? I'm not sure which is correct in DeepFashion, and it need password.
