### ISSUE TITLE
cannot reproduce the result

### ISSUE THREAD

**Issue by SenHe** [cuiaiyu/dressing-in-order#38]
Hi Aiyu,

I followed exactly the same process as you mentioned in the github (I didn't install the cuda function in GFLA as I only need to run the inference stage, and I set --frozen_flownet=True). But the generated results are like this:
![generated_2](https://user-images.githubusercontent.com/25322508/155359613-c0a2bcc0-a050-47e1-b5c4-e1789a47df43.jpg)
![generated_3](https://user-images.githubusercontent.com/25322508/155359642-351b6838-b2fc-4985-9c9d-216a28f31bad.jpg)

**Comment by cuiaiyu** [comment]
Can you check if the input pose/parse are correctly loaded? also please also check if the ```--netG``` and checkpoint are consistent.

**Comment by chenghu0523** [comment]
我遇到相同问题 你是怎么解决的呢
