### ISSUE TITLE
Results are not displayed

### ISSUE THREAD

**Issue by dubbie12** [cuiaiyu/dressing-in-order#39]
Hello, thank you so much for this great work.
I have a problem trying to test the demo on google colab, when I execute the Try-On: Tucking in  although no error is showed I can not see any result
![image](https://user-images.githubusercontent.com/100483804/156221460-ea781189-87e3-434b-8666-46986d90d21b.png)

I also get this when I run the code before, I dont know if this can be related
![image](https://user-images.githubusercontent.com/100483804/156221714-89bd5f7e-c958-4e22-b1cf-dd52a7dd47f3.png)

**Comment by cuiaiyu** [comment]
The notebook has nothing to do with the tensorboard. It is a notebook rendering problem. Try to add ```%matplotlib inline``` in the block you want the images printed

**Comment by dubbie12** [comment]
It worked. Thank you so much
![image](https://user-images.githubusercontent.com/100483804/156356347-9dbe170f-c3c9-40db-89c9-c048c8389a42.png)
