### ISSUE TITLE
Password is required to unzip the img_highres.zip file

### ISSUE THREAD

**Issue by josh-zhu** [cuiaiyu/dressing-in-order#4]
Hi,

Thanks for your great work. Could you share the password for the img_highres.zip file?

**Comment by cuiaiyu** [comment]
Please check the official webpage of deepfashion dataset about the password. http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion.html

http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html
