### ISSUE TITLE
some trouble when running demo

### ISSUE THREAD

**Issue by xuCW1** [cuiaiyu/dressing-in-order#41]
Hi! I successfully practiced the texture transfer in your demo, and I found it very interesting. But when I try to use only a texture image instead of a character image as the source texture, I encounter difficulties, how can I achieve this?I want to achieve the same result as in your paper.Thank you!
![image](https://user-images.githubusercontent.com/75973586/156915073-fb3a6256-438b-4787-a64a-10f4b212b04d.png)

**Comment by cuiaiyu** [comment]
You can replace the garment texture feature with something like ```model.E_attr(my_texture_image)```
