### ISSUE TITLE
Person doesn't look the same in results TryOn

### ISSUE THREAD

**Issue by dubbie12** [cuiaiyu/dressing-in-order#42]
Hello, thank you again for this great job.
I am trying the google colab project with custom images, but the face don't look the same person, even the person appears with a beard, despite the fact that in the input image he did not have.
1. I rezise the input image to 750x1101

3. I generated the 18 keypoints with COCO data set, using this (the input image for open pose was 175x256):
!cd openpose && ./build/examples/openpose/openpose.bin --image_dir '{colab_image_path}' --model_pose COCO --write_json '{colab_openpose_image_path}' --display 0 --render_pose 0

4. I generated the parse image using Human_Parsing_shcp
![oma (3)](https://user-images.githubusercontent.com/100483804/157295884-4c0b29cd-fbc5-42c2-8aa4-a574ca74dc98.png)

But the results are a little weird, as you can se bellow:
![image](https://user-images.githubusercontent.com/100483804/157296468-6e4a242f-d98b-48c8-9418-3dfc82f72696.png)

The fashion dataset looks good
![image](https://user-images.githubusercontent.com/100483804/157317155-7a4a4daa-890e-4b7c-ad9e-a9683ec3f731.png)

Am I doing something wrog or these results are normal? Thank you

**Comment by cuiaiyu** [comment]
That's unfortunately a face overfitting problem as discussed here https://github.com/cuiaiyu/dressing-in-order/issues/32

**Comment by dubbie12** [comment]
Entiendo. Gracias por la rápida respuesta
