### ISSUE TITLE
custom image openpose keypoints

### ISSUE THREAD

**Issue by KIMMUSIC** [cuiaiyu/dressing-in-order#45]
I am testing the custom image. I ran openpose, so I got keypoints json file. but i think it's too big. 
like
x : [445, 376, 189, 111, 153, 556, 589, 574, 282, 279, -1, 463, -1, -1, 403, 466, 324, -1]
y: [180, 382, 373, 655, 884, 391, 697, 941, 914, 1097, -1, 929, -1, -1, 138, 141, 147, -1]

how can i convert this? 
should I use **load_pose_from_json** code? If then, when i get heatmap value, what should I do next?

**Comment by KIMMUSIC** [comment]
Before run openpose, I changed image size 256x176. Then i got corret keypoints. Is it correct method?

**Comment by cuiaiyu** [comment]
Sounds correct. Also this issue https://github.com/cuiaiyu/dressing-in-order/issues/36 has another solution to solve this problem, if you are interested.
