### ISSUE TITLE
flownet.pt not found

### ISSUE THREAD

**Issue by t-qureshi** [cuiaiyu/dressing-in-order#5]
Hi,
Thank You so much for sharing this amazing work. I was thinking to implement your work but I couldn't find flownet.pt. Can you please share the model
Thanks

**Comment by cuiaiyu** [comment]
Hi, thank you for bringing this up. flownet.pt is the pertrained global flow field net. You can obtain it either from training by ```script/run_pose.sh``` (and specify --flownet_path $THE_PATH) or extract the weights of global flow field net from GFLA.

However, if you only wants to run inferences, you shouldn't have needed it, as it would be replaced by "latest_net_Flow.pt" in the checkpoints. I updated the code configuration, so I think it will no longer be a problem.
