### ISSUE TITLE
What's the version of openpose?

### ISSUE THREAD

**Issue by jerry940080** [cuiaiyu/dressing-in-order#51]
Please provide the details of the openpose version, it seems that the version of the openpose would affact the demo result.

**Comment by cuiaiyu** [comment]
The openpose version shouldn't affect the results. Just make sure you are using COCO label (17 joints) rather than the ```body25``` label, which have 25 labels. If you are constrained with ```body 25``` label, please refer to https://github.com/cuiaiyu/dressing-in-order/issues/21
