### ISSUE TITLE
the groups and the persons in them

### ISSUE THREAD

**Issue by maziqueen79** [cuiaiyu/dressing-in-order#55]
hello, first of all i would like to congratulate you for the great work.
I have a question about the used groups(pattern, plaid...), i couldn't understand how were they created and where ? and how are they used to extract poses ?

**Comment by cuiaiyu** [comment]
There are just manually selected examples from deepfashion test split for quick visualization purpose. (During training, we visualize the try-on application every ```opt.display_freq``` iterations from those pre-selected examples in tensorboard)

You can find the annotation here https://drive.google.com/drive/folders/11wWszW1kskAyMIGJHBBZzHNKN3os6pu_
