### ISSUE TITLE
Test Custom Images

### ISSUE THREAD

**Issue by vinodbukya6** [cuiaiyu/dressing-in-order#57]
Thank you so much for your great work. I am trying virtual tryon testing and have img, parse, posekeypoints pairs for target person and garment. Can anyone guide me on how to pass these files to model or inference. Tried using **demo.ipynb** but facing issues.

**Comment by vinodbukya6** [comment]
Hi, I am trying **virtual tryon testing** and have img, parse, posekeypoints pairs for target person and garment.
pimg size: torch.Size([3, 256, 176])
parse size: torch.Size([256, 176, 3])
pose size: torch.Size([18, 256, 176])
[
![image](https://user-images.githubusercontent.com/46157647/184062636-f6f80a67-4b5d-47d0-a35f-8e4a9eb30c5b.png)
](url)

**Comment by ramnithish07** [comment]
Can you post code for custom test image?
