### ISSUE TITLE
Testing on CPU

### ISSUE THREAD

**Issue by vinodbukya6** [cuiaiyu/dressing-in-order#58]
Hi @cuiaiyu, Thank you so much for your work. I am running **demo.ipynb** on CPU machine for virtual tryon. Facing **AttributeError: 'ADGANEncoder' object has no attribute 'module'**

Can you help me on the same.

**Comment by cuiaiyu** [comment]
I personally never tried the code on CPU, but my intuition is to try call it without  ```module``` attribute (by something like ```netE_attr.enc_seg()``` rather than ```netE_attr.module.enc_seg()```), because the ```_init_net()``` wouldn't send model to parallel if there is no GPU, so no the models don't have ```module```.

**Comment by vinodbukya6** [comment]
Hi @cuiaiyu . Thank you so much for response.

I have converted code GPU to CPU by changing here:
```
def init_net(net, init_type='normal', init_gain=0.02, gpu_ids=[], do_init_weight=True):
    """Initialize a network: 1. register CPU/GPU device (with multi-GPU support); 2. initialize the network weights
    Parameters:
        net (network)      -- the network to be initialized
        init_type (str)    -- the name of an initialization method: normal | xavier | kaiming | orthogonal
        gain (float)       -- scaling factor for normal, xavier and orthogonal.
        gpu_ids (int list) -- which GPUs the network runs on: e.g., 0,1,2
    Return an initialized network.
    """
    
    if torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
        
    gpu_ids = [0]
        
    if len(gpu_ids) > 0:
        # import pdb; pdb.set_trace()
        #assert(torch.cuda.is_available())
        
        net = net.cpu()
        net.to(device)
        net = torch.nn.DataParallel(net, device_ids=None)  # multi-GPUs
        
    if do_init_weight:
        init_weights(net, init_type, init_gain=init_gain)
    return net
```

But facing poor performance issue. Will this affect the performance or am I doing anything wrong?

**Comment by cuiaiyu** [comment]
I’m not sure if it causes any changes by running on CPU. 

However, you may want to check if the keypoint is loaded correctly as well, the color of joints and the lines between the joints are not what to expect.

**Comment by vinodbukya6** [comment]
Hi @cuiaiyu
Performance is same as GPU based code.
But I am not able to fetch the Garment images. sample image
![download3](https://user-images.githubusercontent.com/46157647/186206983-63f8841c-7838-4e95-bbc3-f1899746d658.png)

Getting Garment image like this.
![download4](https://user-images.githubusercontent.com/46157647/186207222-d553f6ce-9b75-4b38-88f2-c7a532535aff.png)
