### ISSUE TITLE
Human Parser Issue

### ISSUE THREAD

**Issue by vinodbukya6** [cuiaiyu/dressing-in-order#59]
Hi @cuiaiyu 
I hope you are doing well. 
Can you please help me regarding human parser methods. I have created parser using SCHP(On CPU not working), so using LIP JPPNet Parser(https://github.com/Engineering-Course/LIP_JPPNet). 
Exatracted Parser using SCHP colab notebook and results are Great. Not able to generate same results with LIP JPPNet Parser.

**Is your demo works with any method of Human Parser or only works with SCHP parser(which only works on GPU)?**

Original Image:
![test_men04](https://user-images.githubusercontent.com/46157647/187596023-a4ab6cac-e5ca-4d37-8bbd-c5919332754c.jpg)

SCHP Colab Notebook Result:
![test_men04](https://user-images.githubusercontent.com/46157647/187595637-c17f8fb3-b9c8-45c4-8f47-51f8bc71bf4e.png)

LPP JPPNet Parser Result:
![test_men04](https://user-images.githubusercontent.com/46157647/187595928-42f264ae-cd1d-47d7-b45f-6a222a222163.png)

**Comment by cuiaiyu** [comment]
As long as you have LIP labels (with each category in the same order), you should be good.

If you are different label than LIP, you can change the index of garments and the part of interested in this file. 
https://github.com/cuiaiyu/dressing-in-order/blob/main/datasets/human_parse_labels.py

**Comment by vinodbukya6** [comment]
Hi, everything is working fine. Implemented Human Parser using this GitHub Repo: https://github.com/samuelesabella/Self-Correction-Human-Parsing

Thank you so much.
