### ISSUE TITLE
Dataset password required to run inference in demo?

### ISSUE THREAD

**Issue by gaurav-95** [cuiaiyu/dressing-in-order#60]
Hello, this is amazing work you have here. 

I wanted to know is it absolutely necessary to have the imshop dataset to run inference?
And to use it i'd have to ask the dataset owner for the password? or is there an alternate way of runnning inference without downloading the 7.7 Gb dataset?

Regards,

**Comment by cuiaiyu** [comment]
Hi! You can use your images with the keypoints and human-parse proprocessed. You'll need revise some data I/O code in the demo because the current code in demo assumes that the data will be loaded from DeepFashion dataloader.
