### ISSUE TITLE
Bad results by the pre-trained model when tested on an unseen image

### ISSUE THREAD

**Issue by onchiptech** [cuiaiyu/dressing-in-order#62]
Hello,

I run the "Try-On" task inference with the pre-trained model on the following image which is not in the dataset.

 
![a](https://user-images.githubusercontent.com/31723717/191910611-8a67369f-cfdb-477e-a2c6-c1f37dd46afa.jpg)

As you can see the below output generated is not good. Face and hands are not rendered properly.

![Screenshot from 2022-09-23 12-56-06](https://user-images.githubusercontent.com/31723717/191910858-9344f3b3-08c3-4962-805a-d5cf777b262c.png)

But for the images in the datasets, I am getting good results.

Any suggestions?

Regards,
Surendra

**Comment by cuiaiyu** [comment]
The pretrained model has the face overfitting issue for outlier data. For try-on task, I suggest to directly copy and paste the face as
```
final_img = face_mask * input_img + (1-face_mask) * generated_image.
```
where the face_mask you can get from the human parsing which is part of the inputs.

**Comment by shu0o0yX** [comment]
@vinodbukya6 Hi, could you please share img_highres.zip with me? I'm not sure which is correct in DeepFashion, and it need password.
