### ISSUE TITLE
Traninig models on Viton datasets

### ISSUE THREAD

**Issue by ml1652** [cuiaiyu/dressing-in-order#63]
Hi there,

Thank you for your great work. I would like to ask if it is possible to use Viton to train Dior. In your work, you have used the Deepfashion dataset, there are multiple images of each wearer in different poses whereas in Viton each wearer has only pairs of images of the person's image and its cloth. If it is possible to use Viton dataset to train your work while only changing the dataloader?  I'm not so sure that global flow will work in the Viton case.

Thanks a lot for the great work again!

**Comment by cuiaiyu** [comment]
Hi. The designed model doesn't directly support VITON-like dataset. The person images with paired poses are required to train the models, if you want to maintain all functions. 

One of the reasons behind it is that the GFLA flow isn't designed for garment-person flow but person-person flow. If you only care about the virtual try-on functionality, you can replace the flow model with some other flow predictor. However, in that case, the pose transfer and outfit editting functions will not be maintained, as the model is not trained on pose transfer and there is no multi-garment interaction present in the training to learn outfit editing. 

[This work](https://github.com/shaoyuc3/dior-VTON) has trained DIOR on VITON by replacing the GFLA flow model (person to person flow) with [Flowstyle flow model](https://github.com/SenHe/Flow-Style-VTON) (garment to person flow).
