### ISSUE TITLE
Texture transfer results

### ISSUE THREAD

**Issue by vinodbukya6** [cuiaiyu/dressing-in-order#64]
Hi @cuiaiyu 
I am working on texture transfer demo. Results are not same as given in demo notebook.

Result I got:
![result_tex](https://user-images.githubusercontent.com/46157647/198323010-fcf18d64-e527-4fa3-9c8d-0364e74678d2.jpg)

Demo Result: 
![texture_trans](https://user-images.githubusercontent.com/46157647/198323275-3c8b7942-fb6e-40dd-a002-b72a3732dbdd.png)

How can I improve the performance?

**Comment by cuiaiyu** [comment]
If your setup is correct and you are still not satisfied the result, maybe you can try to retrain the model with a large inpainting task ratio. This will improve the performance of try-on and this editing task but will hurt pose transfer task.
