### ISSUE TITLE
Input Issues

### ISSUE THREAD

**Issue by haider890** [cuiaiyu/dressing-in-order#66]
I ran the demo on notebook but it doesn't ask for input it just gave me output from dataset, Can you please tell me how to give input (model Photo and Shirt photo) on Google Coolab.

**Comment by shahidh568** [comment]
Hello haider I'm trying to install pytorch version 1.0.0 but its not available how did you intsall it

**Comment by cuiaiyu** [comment]
> I ran the demo on notebook but it doesn't ask for input it just gave me output from dataset, Can you please tell me how to give input (model Photo and Shirt photo) on Google Coolab.

The demo code directly loads image from DeepFashion Dataset. If you want to try your own images, you may want to write your own dataloader.

**Comment by cuiaiyu** [comment]
> 

If you don't need to train the flownet and just want to run the inference, you can use a later version of PyTorch.

**Comment by cuiaiyu** [comment]
> Hello haider I'm trying to install pytorch version 1.0.0 but its not available how did you intsall it

If you don't need to train the flownet and just want to run the inference, you can use a later version of PyTorch.
