### ISSUE TITLE
No such file or directory: 'pretrained_models/flownet.pt'

### ISSUE THREAD

**Issue by lanjingweilai** [cuiaiyu/dressing-in-order#74]
I was just tried running the demo.ipynb file, and I got the error.
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained_models/flownet.pt'
I can't find this pretrained_models/flownet.pt. Where did this file come from?I followed the run steps step by step and did not find the file.
This may seem like a silly question, but can someone help me?

**Comment by GALACTICLIMOS** [comment]
let me tell you, this guy on youtube has this code successfully running, i asked for help and he fixed all these issues for me
https://www.youtube.com/watch?v=pRJppKDsZWA&t=37s
