### ISSUE TITLE
Not able to get password for img_highres.zip

### ISSUE THREAD

**Issue by shivansh-chanana** [cuiaiyu/dressing-in-order#75]
Hello, I have mailed the authors with the signed agreement a month ago but I still haven't received any response from them. 
Is there any other way to run a project or find a dataset that is free and easy to integrate? Please help me as I need it for my research paper.
Thank you

**Comment by cuiaiyu** [comment]
Maybe also check this https://github.com/yumingj/DeepFashion-MultiModal
