### ISSUE TITLE
Code running successfully but only once

### ISSUE THREAD

**Issue by ASIFIQBAL5955** [cuiaiyu/dressing-in-order#76]
Hi i was able to run code successfully. sometime kernal cashes for no reason. can i get you whatsapp ? Please reach me at my whatsapp +923057736599 or mail asif5955iqbal@yahoo,com
i can also set this up for anyone having issues

**Comment by ASIFIQBAL5955** [comment]
it is working almost stable. need a little bit improvement

**Comment by ASIFIQBAL5955** [comment]
i will be uploading a demo video on my channel
https://www.youtube.com/watch?v=hS_XQgI69kE

**Comment by cuiaiyu** [comment]
I am closing this issue because no actual problem was described.
