### ISSUE TITLE
The code is running successfully but only on google colab. how to run on local machine by saving model?

### ISSUE THREAD

**Issue by ASIFIQBAL5955** [cuiaiyu/dressing-in-order#77]
i was able to run this code using google colab and cuda. Now i want to test it on local machine but i am unable to save model so i dont have to train again and again. please help me

Regards: asif iqbal
my whatsapp: +92-305-7736599
my mail: asif5955iqbal@yahoo.com
i will be uploading a demo video on my channel 
https://www.youtube.com/watch?v=hS_XQgI69kE

**Comment by ASIFIQBAL5955** [comment]
i will be uploading a demo video on my channel 
https://www.youtube.com/watch?v=hS_XQgI69kE

**Comment by ASIFIQBAL5955** [comment]
Please check this link, all issues have been resolved.
video demo
https://www.youtube.com/watch?v=pRJppKDsZWA&ab_channel=AISOFT

**Comment by cuiaiyu** [comment]
I am closing this issue because no actual problem was described.
