### ISSUE TITLE
What is $DATA_DIR in run_eval.sh file if I rerun all the training processing with DFashion dataset ?

### ISSUE THREAD

**Issue by phuongtrau** [cuiaiyu/dressing-in-order#78]
What is $DATA_DIR in run_eval.sh file if I rerun all the training processing with the DFashion dataset?

**Comment by ASIFIQBAL5955** [comment]
Please check this link, all issues have been resolved by this guy. ask him
video demo
https://www.youtube.com/watch?v=pRJppKDsZWA&ab_channel=AISOFT

**Comment by cuiaiyu** [comment]
> What is $DATA_DIR in run_eval.sh file if I rerun all the training processing with the DFashion dataset?

It should be the path to the folder where deepfashion data is stored.
