### ISSUE TITLE
Third-Party Colab Setup Progress

### ISSUE THREAD

**Issue by ASIFIQBAL5955** [cuiaiyu/dressing-in-order#79]
Please check this link, all issues have been resolved for this project by this Guy.
video demo
https://www.youtube.com/watch?v=pRJppKDsZWA&ab_channel=AISOFT

**Comment by cuiaiyu** [comment]
Thanks for your interests in our work. However, the image output results in the shown YouTube video is not our expected results. Especially, the transferred garment does not look like correct. There is bug in your implementation.


For example, the result in the below screenshot is not the expected output. The garment is not warped correctly.
![0B4ADF0A-BC42-4B07-8545-6F5B288B04B5](https://user-images.githubusercontent.com/19510154/232237648-3ab6c041-0caf-4dec-bd19-91de32116831.png)

**Comment by ASIFIQBAL5955** [comment]
Hey how are? First of all thank you sooooooo soooo much for making this great project. i have learned deep learning but not as expert as you guys are. I was so happy to just run the code as per guidelines. i ran into many errors and fixed them one by one.Please give me your whatsapp as you are super awesome. i will stay in touch with you. Are you guys improving it or it was just a final year project?    On Saturday, April 15, 2023 at 09:25:16 PM GMT+5, Aiyu Cui ***@***.***> wrote:  
 
 


Thanks for your interests in our work. However, the image output results in the shown YouTube video is not our expected results. Especially, the transferred garment does not look like correct. There is bug in your implementation.

For example, the result in the below screenshot is not the expected output. The garment is not warped correctly.

**Comment by cuiaiyu** [comment]
Let’s keep the implementation communication within this issue post. Feel free to post the encountered problems here. We will solve the issues based on our availability and priority.

Because the result in the shared YouTube video is not what to expect so far and this is not an official replication, I changed the title from “all problems are solved for this project” to “third-party colab setup progress” in order to avoid misunderstanding.

**Comment by cuiaiyu** [comment]
I lock this post because it contains misinformation that "all issues have been resolved for this project" and the linked
