### ISSUE TITLE
Typo in repo download file.

### ISSUE THREAD

**Issue by aravind-h-v** [cuiaiyu/dressing-in-order#85]
The 'tools/download_deepfashion_from_google_drive.py' has a typo, attaching the required correction:

os.system("mv {} {}".format(args.dataroot + "/images/"+fn, "args.dataroot + "/test/"+new_fn))
should be:
os.system("mv {} {}".format(args.dataroot + "/images/"+fn, args.dataroot + "/test/"+new_fn))

and:

os.system("mv {} {}".format(args.dataroot + "/images/"+fn, "args.dataroot + "/train/"+new_fn))
should be:
os.system("mv {} {}".format(args.dataroot + "/images/"+fn, args.dataroot + "/train/"+new_fn))

**Comment by cuiaiyu** [comment]
fixed. thanks!
