### ISSUE TITLE
Not showing the output images while code is running

### ISSUE THREAD

**Issue by MAmmarRaza** [cuiaiyu/dressing-in-order#90]
Dear Researcher, i am trying to run the demo but i am feeling trouble here when i run this code, it ran fine but not shown the output images, like poses, dresses etc while i ran all recent cells acurately if i am not wrong. Please help me thank you very much for your efforts.
![Screenshot from 2023-09-10 20-48-35](https://github.com/cuiaiyu/dressing-in-order/assets/115019645/bb3204ba-9d35-4a85-a75e-6805ca33e189)

**Comment by cuiaiyu** [comment]
Please run `%matplotlib inline` in the notebook before plotting.
